USE EMPRESA
GO

CREATE TABLE TB_ALUNO(
	IDALUNO INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(30) NOT NULL,
	SEXO CHAR(1) NOT NULL,
	NASCIMENTO DATE NOT NULL,
	EMAIL VARCHAR(30) UNIQUE
)
GO

ALTER TABLE TB_ALUNO
ADD CONSTRAINT CK_SEXO CHECK (SEXO IN('M','F'))
GO

CREATE TABLE TB_ENDERECO(
	IDENDERECO INT PRIMARY KEY IDENTITY(100,10),
	BAIRRO VARCHAR(30),
	UF CHAR(2) NOT NULL
	CHECK (UF IN('RJ','SP','MG')),
	ID_ALUNO INT UNIQUE
)
GO

ALTER TABLE TB_ENDERECO ADD CONSTRAINT FK_TB_ENDERECO_TB_ALUNO
FOREIGN KEY(ID_ALUNO) REFERENCES TB_ALUNO(IDALUNO)
GO

SP_COLUMNS TB_ALUNO
GO

SP_HELP TB_ALUNO
GO

INSERT INTO TB_ALUNO VALUES('ANDRE','M','1981/12/09','ANDRE@IG.COM')
INSERT INTO TB_ALUNO VALUES('ANA','F','1978/03/09','ANA@IG.COM')
INSERT INTO TB_ALUNO VALUES('RUI','M','1951/07/09','RUI@IG.COM')
INSERT INTO TB_ALUNO VALUES('JOAO','M','2002/11/09','JOAO@IG.COM')
GO

SELECT * FROM TB_ALUNO
SELECT * FROM TB_ENDERECO

INSERT INTO TB_ENDERECO VALUES('FLAMENGO','RJ',1)
INSERT INTO TB_ENDERECO VALUES('MORUMBI','SP',2)
INSERT INTO TB_ENDERECO VALUES('CENTRO','MG',4)
INSERT INTO TB_ENDERECO VALUES('CENTRO','SP',3)
GO

CREATE TABLE TB_TELEFONE(
	IDTELEFONE INT PRIMARY KEY IDENTITY,
	TIPO CHAR(3) NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	ID_ALUNO INT,
	CHECK (TIPO IN ('RES','COM','CEL'))
)
GO

ALTER TABLE TB_TELEFONE ADD CONSTRAINT FK_TB_TELEFONE_TB_ALUNO
FOREIGN KEY(ID_ALUNO) REFERENCES TB_ALUNO(IDALUNO)
GO

INSERT INTO TB_TELEFONE VALUES('CEL','7899889',1)
INSERT INTO TB_TELEFONE VALUES('RES','4325444',1)
INSERT INTO TB_TELEFONE VALUES('COM','4354354',2)
INSERT INTO TB_TELEFONE VALUES('CEL','2344556',2)
GO

SELECT 
	A.NOME, 
	ISNULL(T.TIPO,'SEM'), 
	ISNULL(T.NUMERO,'NUMERO'), 
	E.BAIRRO, 
	E.UF
FROM TB_ALUNO A
LEFT JOIN TB_TELEFONE T
ON A.IDALUNO = T.ID_ALUNO
INNER JOIN TB_ENDERECO E
ON A.IDALUNO = E.ID_ALUNO
GO

SELECT NOME, (DATEDIFF(DAY,NASCIMENTO,GETDATE())/365) AS IDADE
FROM TB_ALUNO
GO

SELECT NOME, DATEDIFF(YEAR,NASCIMENTO,GETDATE()) AS IDADE
FROM TB_ALUNO
GO

